export type KernelSourceTerm = {
  label: string
  path: string
  line?: number
  endLine?: number
  symbol?: string
  note?: string
}

export const kernelSourceTerms: Record<string, KernelSourceTerm> = {
  start_kernel: {
    label: 'start_kernel',
    path: 'init/main.c',
    line: 1017,
    endLine: 1044,
    symbol: 'start_kernel',
    note: '内核 C 入口',
  },
  init_task: {
    label: 'init_task',
    path: 'include/linux/init_task.h',
    symbol: 'init_task',
    note: 'PID 0 的静态 task_struct',
  },
  task_struct: {
    label: 'task_struct',
    path: 'include/linux/sched.h',
    line: 820,
    endLine: 850,
    symbol: 'task_struct',
    note: '进程描述符',
  },
  state: {
    label: 'state',
    path: 'include/linux/sched.h',
    line: 828,
    endLine: 836,
    symbol: '__state',
    note: '进程状态字段',
  },
  __state: {
    label: '__state',
    path: 'include/linux/sched.h',
    line: 828,
    endLine: 836,
    symbol: '__state',
    note: '进程状态字段',
  },
  pid: {
    label: 'pid',
    path: 'include/linux/sched.h',
    line: 1060,
    endLine: 1061,
    symbol: 'pid',
    note: '进程 ID',
  },
  tgid: {
    label: 'tgid',
    path: 'include/linux/sched.h',
    line: 1060,
    endLine: 1061,
    symbol: 'tgid',
    note: '线程组 ID',
  },
  real_parent: {
    label: 'real_parent',
    path: 'include/linux/sched.h',
    line: 1068,
    endLine: 1077,
    symbol: 'real_parent',
    note: '真实父进程指针',
  },
  parent: {
    label: 'parent',
    path: 'include/linux/sched.h',
    line: 1068,
    endLine: 1077,
    symbol: 'parent',
    note: '当前父进程指针',
  },
  children: {
    label: 'children',
    path: 'include/linux/sched.h',
    line: 1080,
    endLine: 1084,
    symbol: 'children',
    note: '子进程链表',
  },
  sibling: {
    label: 'sibling',
    path: 'include/linux/sched.h',
    line: 1080,
    endLine: 1084,
    symbol: 'sibling',
    note: '兄弟进程链表',
  },
  comm: {
    label: 'comm',
    path: 'include/linux/sched.h',
    line: 1170,
    endLine: 1170,
    symbol: 'comm',
    note: '任务名字段',
  },
  prio: {
    label: 'prio',
    path: 'include/linux/sched.h',
    line: 866,
    endLine: 868,
    symbol: 'prio',
    note: '进程优先级字段',
  },
  static_prio: {
    label: 'static_prio',
    path: 'include/linux/sched.h',
    line: 866,
    endLine: 868,
    symbol: 'static_prio',
    note: '静态优先级字段',
  },
  normal_prio: {
    label: 'normal_prio',
    path: 'include/linux/sched.h',
    line: 866,
    endLine: 868,
    symbol: 'normal_prio',
    note: '普通优先级字段',
  },
  policy: {
    label: 'policy',
    path: 'include/linux/sched.h',
    line: 920,
    endLine: 920,
    symbol: 'policy',
    note: '调度策略字段',
  },
  se: {
    label: 'se',
    path: 'include/linux/sched.h',
    line: 871,
    endLine: 871,
    symbol: 'se',
    note: 'CFS 调度实体字段',
  },
  mm: {
    label: 'mm',
    path: 'include/linux/sched.h',
    line: 962,
    endLine: 963,
    symbol: 'mm',
    note: '用户地址空间描述符指针',
  },
  mm_struct: {
    label: 'mm_struct',
    path: 'include/linux/mm_types.h',
    line: 1172,
    endLine: 1202,
    symbol: 'mm_struct',
    note: '进程地址空间描述符',
  },
  files: {
    label: 'files',
    path: 'include/linux/sched.h',
    line: 1186,
    endLine: 1186,
    symbol: 'files',
    note: '打开文件表指针',
  },
  files_struct: {
    label: 'files_struct',
    path: 'include/linux/fdtable.h',
    line: 38,
    endLine: 63,
    symbol: 'files_struct',
    note: '打开文件表',
  },
  signal: {
    label: 'signal',
    path: 'include/linux/sched.h',
    line: 1197,
    endLine: 1197,
    symbol: 'signal',
    note: '线程组共享信号状态',
  },
  signal_struct: {
    label: 'signal_struct',
    path: 'include/linux/sched/signal.h',
    line: 94,
    endLine: 124,
    symbol: 'signal_struct',
    note: '信号状态结构',
  },
  fs: {
    label: 'fs',
    path: 'include/linux/sched.h',
    line: 1183,
    endLine: 1183,
    symbol: 'fs',
    note: '文件系统上下文字段',
  },
  fs_struct: {
    label: 'fs_struct',
    path: 'include/linux/fs_struct.h',
    line: 10,
    endLine: 18,
    symbol: 'fs_struct',
    note: '文件系统上下文结构',
  },
  f_pos: {
    label: 'f_pos',
    path: 'include/linux/fs.h',
    line: 1282,
    endLine: 1282,
    symbol: 'f_pos',
    note: '文件当前位置',
  },
  f_mode: {
    label: 'f_mode',
    path: 'include/linux/fs.h',
    line: 1262,
    endLine: 1263,
    symbol: 'f_mode',
    note: '文件打开模式',
  },
  file_operations: {
    label: 'file_operations',
    path: 'include/linux/fs.h',
    line: 1926,
    endLine: 1960,
    symbol: 'file_operations',
    note: '文件操作表',
  },
  sighand: {
    label: 'sighand',
    path: 'include/linux/sched.h',
    line: 1196,
    endLine: 1197,
    symbol: 'sighand',
    note: '信号处理表指针',
  },
  sighand_struct: {
    label: 'sighand_struct',
    path: 'include/linux/sched/signal.h',
    line: 21,
    endLine: 27,
    symbol: 'sighand_struct',
    note: '信号处理表',
  },
  cred: {
    label: 'cred',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 132,
    symbol: 'cred',
    note: '凭证结构',
  },
  uid: {
    label: 'uid',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 123,
    symbol: 'uid',
    note: '真实用户 ID',
  },
  euid: {
    label: 'euid',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 123,
    symbol: 'euid',
    note: '有效用户 ID',
  },
  gid: {
    label: 'gid',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 123,
    symbol: 'gid',
    note: '真实组 ID',
  },
  egid: {
    label: 'egid',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 123,
    symbol: 'egid',
    note: '有效组 ID',
  },
  ptrace: {
    label: 'ptrace',
    path: 'include/linux/sched.h',
    line: 843,
    endLine: 843,
    symbol: 'ptrace',
    note: 'ptrace 状态字段',
  },
  setuid: {
    label: 'setuid',
    path: 'include/linux/cred.h',
    line: 115,
    endLine: 123,
    symbol: 'euid',
    note: 'setuid 机制影响有效 UID',
  },
  copy_process: {
    label: 'copy_process',
    path: 'kernel/fork.c',
    line: 1969,
    endLine: 2005,
    symbol: 'copy_process',
    note: '进程复制核心路径',
  },
  kernel_clone: {
    label: 'kernel_clone',
    path: 'kernel/fork.c',
    line: 2670,
    endLine: 2705,
    symbol: 'kernel_clone',
    note: 'clone/fork 内核入口',
  },
  kthreadd: {
    label: 'kthreadd',
    path: 'kernel/fork.c',
    symbol: 'kthreadd',
    note: '内核线程守护进程',
  },
}
