FROM emscripten/emsdk:3.1.51

# 安装额外工具
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    gcc-riscv64-linux-gnu \
    libc6-dev-riscv64-cross \
    qemu-user \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY compile-all.sh /build/compile-all.sh
RUN chmod +x /build/compile-all.sh

ENTRYPOINT ["/build/compile-all.sh"]
